In [1]:
import numpy as np

In [43]:
x = np.array([0,0,1,0.1,1,1,1,0.2,1,1,1,1]).reshape(4,3)
fx = np.array([0,0.41,0.18,0.5]).reshape(4,-1)
theta = np.linalg.solve(x.T@x,x.T@fx)
print(theta)

[[ 1.00000000e-01]
 [ 4.00000000e-01]
 [-1.65234042e-16]]


In [47]:
x@theta

array([[-1.65234042e-16],
       [ 4.10000000e-01],
       [ 1.80000000e-01],
       [ 5.00000000e-01]])

In [33]:
x_ = np.array([0,0,1,0.1,1,1,1,0.2,1,1,1,1]).reshape(4,3)
y = np.array([-0.0416,0.3610,0.1222,0.4733]).reshape(4,-1)
theta_ = np.linalg.solve(x_.T@x_,x_.T@y)
print(theta_)

[[ 0.10107389]
 [ 0.41070998]
 [-0.05022928]]


In [45]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(fx,x@theta))
mean_squared_error(y,x_@theta)

1.3758919939609661e-32


0.0020463224999999964

In [51]:
xx = np.array([0,0,0,1,1,0,1,1]).reshape(4,2)
yx = np.array([0,1,1,1]).reshape(4,1)
thetax = np.linalg.solve(xx.T@xx,xx.T@yx)
print(thetax)

[[0.66666667]
 [0.66666667]]


In [54]:
a = np.array([1,1,1,1]).reshape(2,2)
b = np.array([0,0,1,1,0,1,0,1]).reshape(2,4)
e = np.array([0,-1]).reshape(2,1)
h = a@b+e
print(h)

[[ 0  1  1  2]
 [-1  0  0  1]]
